name: colored_log
description: An awesome logging package for dart. Makes debugging and development more interesting
repository: https://github.com/thisisprabhat/colored_log.git
homepage: https://github.com/thisisprabhat/colored_log.git
version: 1.3.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.8.0+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
- cli
- logging
- debug
- color
- console

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

license: MIT