name: colored_log
description: An awesome logging package for dart. Makes debugging and development more interesting
version: 1.0.0
repository: https://github.com/thisisprabhat/colored_log.git

environment:
  sdk: ^3.6.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
